# Generated by Django 4.2.2 on 2023-08-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='small_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
