# Generated by Django 4.2.2 on 2023-08-27 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_product_color_product_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='color',
            new_name='colors',
        ),
    ]
