# Generated by Django 4.2.5 on 2023-10-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contactus_emaillist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='email',
            field=models.CharField(unique=True),
        ),
    ]
