# Generated by Django 4.2.5 on 2023-10-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_emaillist_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
